### ISSUE TITLE
issues installing

### ISSUE THREAD

**Issue by mkborregaard** [JuliaGPU/CuArrays.jl#155]
Not sure whether this should be opened here or elsewhere. I am having issues installing.
```
(v1.0) pkg> test CuArrays
   Testing CuArrays
 Resolving package versions...
....
ERROR: LoadError: InitError: TypeError: in ccall, expected Symbol, got Nothing
Stacktrace:
 [1] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:630
 [2] macro expansion at ./logging.jl:312 [inlined]
 [3] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:701
 [4] _require(::Base.PkgId) at ./loading.jl:934
 [5] require(::Base.PkgId) at ./loading.jl:855
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:837
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1041
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] exec_options(::Base.JLOptions) at ./client.jl:229
 [12] _start() at ./client.jl:421
during initialization of module CURAND
in expression starting at /home/michael/.julia/packages/CuArrays/clDeS/test/runtests.jl:16
TypeError(:ccall, "", Symbol, nothing)
TypeError(:ccall, "", Symbol, nothing)
ERROR: LoadError: failed process: Process(`/home/michael/github/julia/usr/bin/julia -Cnative -J/home/michael/github/julia/usr/lib/julia/sys.so --compile=yes --depwarn=yes --color=yes --compiled-modules=yes --startup-file=no --code-coverage=none /home/michael/.julia/packages/CuArrays/clDeS/test/runtests.jl`, ProcessExited(1)) [1]
Stacktrace:
 [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
 [2] pipeline_error at ./process.jl:705 [inlined]
 [3] #run#504(::Bool, ::Function, ::Cmd) at ./process.jl:663
 [4] run(::Cmd) at ./process.jl:661
 [5] top-level scope at /home/michael/.julia/packages/CuArrays/clDeS/test/runtests.jl:5
 [6] include at ./boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1041
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] include(::String) at ./client.jl:388
 [10] top-level scope at none:0
in expression starting at /home/michael/.julia/packages/CuArrays/clDeS/test/runtests.jl:3
ERROR: Package CuArrays errored during testing

julia> using CuArrays
ERROR: InitError: TypeError: in ccall, expected Symbol, got Nothing
Stacktrace:
 [1] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:630
 [2] macro expansion at ./logging.jl:312 [inlined]
 [3] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:701
 [4] _require(::Base.PkgId) at ./loading.jl:934
 [5] require(::Base.PkgId) at ./loading.jl:855
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:837
during initialization of module CURAND
```
CUDAapi and CUDAdrv tests pass, but on CUDAnative 2 tests error
```
(v1.0) pkg> test CUDAnative
   Testing CUDAnative
 Resolving package versions...
    Status `/tmp/tmpJSCPcA/Manifest.toml`
  [3895d2a7] CUDAapi v0.5.2
  [c5f51814] CUDAdrv v0.8.6
  [be33ccc6] CUDAnative v0.9.1
  [929cbde3] LLVM v0.9.15
  [2a0f44e3] Base64  [`@stdlib/Base64`]
  [ade2ca70] Dates  [`@stdlib/Dates`]
  [8ba89e20] Distributed  [`@stdlib/Distributed`]
  [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
  [76f85450] LibGit2  [`@stdlib/LibGit2`]
  [8f399da3] Libdl  [`@stdlib/Libdl`]
  [37e2e46d] LinearAlgebra  [`@stdlib/LinearAlgebra`]
  [56ddb016] Logging  [`@stdlib/Logging`]
  [d6f4376e] Markdown  [`@stdlib/Markdown`]
  [44cfe95a] Pkg  [`@stdlib/Pkg`]
  [de0858da] Printf  [`@stdlib/Printf`]
  [3fa0cd96] REPL  [`@stdlib/REPL`]
  [9a3f8284] Random  [`@stdlib/Random`]
  [ea8e919c] SHA  [`@stdlib/SHA`]
  [9e88b42a] Serialization  [`@stdlib/Serialization`]
  [6462fe0b] Sockets  [`@stdlib/Sockets`]
  [2f01184e] SparseArrays  [`@stdlib/SparseArrays`]
  [10745b16] Statistics  [`@stdlib/Statistics`]
  [8dfed614] Test  [`@stdlib/Test`]
  [cf7118a7] UUIDs  [`@stdlib/UUIDs`]
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]
[ Info: Testing using device Quadro K600
indexing: Error During Test at /home/michael/.julia/packages/CUDAnative/AGfq2/test/device/pointer.jl:31
  Got exception outside of a @test
  CUDA error: a PTX JIT compilation failed (code #218, ERROR_INVALID_PTX)
  ptxas application ptx input, line 31; error   : Instruction 'ld.nc' requires .target sm_32 or higher
  ptxas application ptx input, line 36; error   : Instruction 'ld.nc' requires .target sm_32 or higher
  ptxas fatal   : Ptx assembly aborted due to errors
  Stacktrace:
   [1] CuModule(::String, ::Dict{CUDAdrv.CUjit_option,Any}) at ./logging.jl:314
   [2] #cufunction#77(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::CuDevice, ::Any, ::Any) at /home/michael/.julia/packages/CUDAnative/AGfq2/src/compiler/driver.jl:31
   [3] cufunction at /home/michael/.julia/packages/CUDAnative/AGfq2/src/compiler/driver.jl:10 [inlined]
   [4] macro expansion at /home/michael/.julia/packages/CUDAnative/AGfq2/src/execution.jl:180 [inlined]
   [5] _cuda(::typeof(issue_221), ::Tuple{}, ::Tuple{}, ::CUDAnative.DevicePtr{Complex{Int8},CUDAnative.AS.Global}, ::CUDAnative.DevicePtr{Complex{Int8},CUDAnative.AS.Global}) at /home/michael/.julia/packages/CUDAnative/AGfq2/src/execution.jl:139
   [6] top-level scope at /home/michael/github/julia/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1156
   [7] include at ./boot.jl:317 [inlined]
   [8] include_relative(::Module, ::String) at ./loading.jl:1041
   [9] include(::Module, ::String) at ./sysimg.jl:29
   [10] include(::String) at ./client.jl:388
   [11] macro expansion at ./logging.jl:312 [inlined]
   [12] macro expansion at /home/michael/.julia/packages/CUDAnative/AGfq2/test/runtests.jl:55 [inlined]
   [13] macro expansion at /home/michael/github/julia/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
   [14] top-level scope at /home/michael/.julia/packages/CUDAnative/AGfq2/test/runtests.jl:8
   [15] include at ./boot.jl:317 [inlined]
   [16] include_relative(::Module, ::String) at ./loading.jl:1041
   [17] include(::Module, ::String) at ./sysimg.jl:29
   [18] include(::String) at ./client.jl:388
   [19] top-level scope at none:0
   [20] eval(::Module, ::Any) at ./boot.jl:319
   [21] macro expansion at ./logging.jl:317 [inlined]
   [22] exec_options(::Base.JLOptions) at ./client.jl:219
   [23] _start() at ./client.jl:421
ldg: Error During Test at /home/michael/.julia/packages/CUDAnative/AGfq2/test/device/array.jl:149
  Got exception outside of a @test
  CUDA error: a PTX JIT compilation failed (code #218, ERROR_INVALID_PTX)
  ptxas application ptx input, line 111; error   : Instruction 'ld.nc' requires .target sm_32 or higher
  ptxas fatal   : Ptx assembly aborted due to errors
  Stacktrace:
   [1] CuModule(::String, ::Dict{CUDAdrv.CUjit_option,Any}) at ./logging.jl:314
   [2] #cufunction#77(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::CuDevice, ::Any, ::Any) at /home/michael/.julia/packages/CUDAnative/AGfq2/src/compiler/driver.jl:31
   [3] cufunction at /home/michael/.julia/packages/CUDAnative/AGfq2/src/compiler/driver.jl:10 [inlined]
   [4] macro expansion at /home/michael/.julia/packages/CUDAnative/AGfq2/src/execution.jl:180 [inlined]
   [5] _cuda(::typeof(array_cached_load), ::Tuple{}, ::Tuple{}, ::CuDeviceArray{Int64,1,CUDAnative.AS.Global}, ::CuDeviceArray{Int64,1,CUDAnative.AS.Global}, ::Int64) at /home/michael/.julia/packages/CUDAnative/AGfq2/src/execution.jl:139
   [6] macro expansion at /home/michael/.julia/packages/CUDAnative/AGfq2/test/device/array.jl:41 [inlined]
   [7] macro expansion at /home/michael/github/julia/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
   [8] macro expansion at /home/michael/.julia/packages/CUDAnative/AGfq2/test/device/array.jl:5 [inlined]
   [9] macro expansion at /home/michael/github/julia/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
   [10] top-level scope at /home/michael/.julia/packages/CUDAnative/AGfq2/test/device/array.jl:3
   [11] include at ./boot.jl:317 [inlined]
   [12] include_relative(::Module, ::String) at ./loading.jl:1041
   [13] include(::Module, ::String) at ./sysimg.jl:29
   [14] include(::String) at ./client.jl:388
   [15] macro expansion at ./logging.jl:313 [inlined]
   [16] macro expansion at /home/michael/.julia/packages/CUDAnative/AGfq2/test/runtests.jl:55 [inlined]
   [17] macro expansion at /home/michael/github/julia/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
   [18] top-level scope at /home/michael/.julia/packages/CUDAnative/AGfq2/test/runtests.jl:8
   [19] include at ./boot.jl:317 [inlined]
   [20] include_relative(::Module, ::String) at ./loading.jl:1041
   [21] include(::Module, ::String) at ./sysimg.jl:29
   [22] include(::String) at ./client.jl:388
   [23] top-level scope at none:0
   [24] eval(::Module, ::Any) at ./boot.jl:319
   [25] macro expansion at ./logging.jl:317 [inlined]
   [26] exec_options(::Base.JLOptions) at ./client.jl:219
   [27] _start() at ./client.jl:421
Test Summary:                            | Pass  Error  Total
CUDAnative                               |  250      2    252
  base interface                         |              No tests
  pointer                                |   20            20
  code generation                        |   80            80
  code generation (relying on a device)  |    5             5
  execution                              |   34            34
  pointer (on device)                    |   40      1     41
    unsafe_load & unsafe_store!          |   40      1     41
      T = Int8, cached = false           |    2             2
      T = Int8, cached = true            |    2             2
      T = UInt16, cached = false         |    2             2
      T = UInt16, cached = true          |    2             2
      T = Int32, cached = false          |    2             2
      T = Int32, cached = true           |    2             2
      T = UInt32, cached = false         |    2             2
      T = UInt32, cached = true          |    2             2
      T = Int64, cached = false          |    2             2
      T = Int64, cached = true           |    2             2
      T = UInt64, cached = false         |    2             2
      T = UInt64, cached = true          |    2             2
      T = Int128, cached = false         |    2             2
      T = Int128, cached = true          |    2             2
      T = Float32, cached = false        |    2             2
      T = Float32, cached = true         |    2             2
      T = Float64, cached = false        |    2             2
      T = Float64, cached = true         |    2             2
      T = LoadableStruct, cached = false |    2             2
      T = LoadableStruct, cached = true  |    2             2
      indexing                           |           1      1
  device arrays                          |   21      1     22
    constructors                         |   14            14
    basics                               |    1             1
    iteration                            |    1             1
    bounds checking                      |    4             4
    views                                |    1             1
    bug: non-Int index to unsafe_load    |              No tests
    ldg                                  |           1      1
  intrinsics                             |   38            38
  examples                               |    7             7
ERROR: LoadError: Some tests did not pass: 250 passed, 0 failed, 2 errored, 0 broken.
in expression starting at /home/michael/.julia/packages/CUDAnative/AGfq2/test/runtests.jl:6
ERROR: Package CUDAnative errored during testing
```
I'm on a julia 1.01 (built from source) on Ubuntu 18.04
```
julia> versioninfo()
Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
```
Which steps can I take to debug?

**Comment by maleadt** [comment]
Make sure CuArrays is the latest version and try rebuilding. Post the build log and contents of ext.jl if it still fails.

**Comment by maleadt** [comment]
That CUDAnative failure is also fixed on the latest tagged release, so probably out of date too?

**Comment by mkborregaard** [comment]
I literally built julia from source this morning, installed cuda tools 10.0 from NVidia, then `add CUDAapi CUDAdrv CUDAnative CuArrays GPUArrays` installing no other packages, so I should be on the tagged versions. I can't check or create build logs before Monday, unfortunately, as this is a workstation at work.

**Comment by maleadt** [comment]
Yeah, package versions would be useful. For reference, the CUDAnative issue should have been fixed in https://github.com/JuliaGPU/CUDAnative.jl/commit/861c7b981530db217195d03a468a335c792cdb4b#diff-098f6bcd4621d373cade4e832627b4f6.

Concerning CuArrays, the additional check & warn (https://github.com/JuliaGPU/CuArrays.jl/commit/ffe6ec4b476b52dd46e9075022a79c066f81a296#diff-44f85496bf6930d196d5904271343563) isn't part of a tagged release yet, so build.log won't contain anything useful. Try rebuilding CuArrays with `JULIA_DEBUG=CUDAapi` and posting the resulting verbose output.

**Comment by mkborregaard** [comment]
Hey, rebuilding worked, thanks a lot! I don't know what the issue was, as I am on the latest versions. Also of CUDAnative, btw, and the test errors persist there. Do you need an issue about that on CUDAnative?

**Comment by maleadt** [comment]
Great!

> Do you need an issue about that on CUDAnative?

Yes, please. Add the package versions and the output of `capability.(collect(devices()))` (after using CUDAdrv and CUDAnative).
